<a href="https://colab.research.google.com/github/madonnaojorin/MAT343_Linear_Algebra/blob/main/4-6_Rank_of_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#4.6. Rank of a Matrix and Systems of Linear Equations

In [ ]:
install.packages("pracma")
library(pracma)

##Definitions of Row Space and Column Space of a Matrix
Let $A$ be an $m\times n$ matrix.
1. The **row space** of $A$ is the subspace of $\mathbb{R}^n$ spanned by the row vectors of $A$.
2. The **column space** of $A$ is the subspace of $\mathbb{R}^m$ spanned by the column vectors of $A$.

###Theorem 4.13: Row-Equivalent Matrices Have the Same Row Space
If an $m\times n$ matrix $A$ is row-equivalent to an $m\times n$ matrix $B$, then the row space of $A$ is equal to the row space of $B$.

###Theorem 4.14: Basis for the Row Space of a Matrix
If a matrix $A$ is row-equivalent to a matrix $B$ in row-echelon form, then the nonzero row vectors of $B$ form a basis for the row space of $A$.

In [ ]:
# Find a basis for the row space of a matrix A

A <- matrix(c(1,3,1,3,0,1,1,0,-3,0,6,-1,3,4,-2,1,2,0,-4,-2), 5, 4, byrow = TRUE)
A
B <- rref(A)
B

[,1] [,2] [,3] [,4]
[1,]  1   3     1    3  
[2,]  0   1     1    0  
[3,] -3   0     6   -1  
[4,]  3   4    -2    1  
[5,]  2   0    -4   -2

[,1] [,2] [,3] [,4]
[1,] 1    0    -2   0   
[2,] 0    1     1   0   
[3,] 0    0     0   1   
[4,] 0    0     0   0   
[5,] 0    0     0   0

By Theorem 4.14, the nonzero row vectors of $B$, $\textbf{w}_1=\langle1,0,-2,0\rangle$, $\textbf{w}_2=\langle0,1,1,0\rangle$, and $\textbf{w}_3=\langle0,0,0,1\rangle$, form a basis for the row space of $A$.



In [ ]:
# Find a basis for the column space of a matrix A using Method 1

A <- matrix(c(1,3,1,3,0,1,1,0,-3,0,6,-1,3,4,-2,1,2,0,-4,-2), 5, 4, byrow = TRUE)
A_T <- t(A)
A_T
B <- rref(A_T)
B

[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    -3    3    2  
[2,] 3    1     0    4    0  
[3,] 1    1     6   -2   -4  
[4,] 3    0    -1    1   -2

[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    0     0   -1  
[2,] 0    1    0     4    3  
[3,] 0    0    1    -1   -1  
[4,] 0    0    0     0    0

####Method 1
Use the fact that the column space of $A$ is equal to the row space of $A^T$ and apply the technique we used to the find row space.

A basis for the column space of $A$ consists of vectors

$\begin{bmatrix}1\\0\\0\\0\\-1\end{bmatrix}, \begin{bmatrix}0\\1\\0\\4\\3\end{bmatrix}, \begin{bmatrix}0\\0\\1\\-1\\-1\end{bmatrix}$ 

In [ ]:
# Find a basis for the column space of a matrix A using Method 2

A <- matrix(c(1,3,1,3,0,1,1,0,-3,0,6,-1,3,4,-2,1,2,0,-4,-2), 5, 4, byrow = TRUE)
B <- rref(A)
B

[,1] [,2] [,3] [,4]
[1,] 1    0    -2   0   
[2,] 0    1     1   0   
[3,] 0    0     0   1   
[4,] 0    0     0   0   
[5,] 0    0     0   0

####Method 2
Use the fact that although row operations can change the column space of a matrix, they do not change the dependency relationships among columns.


A basis for the column space of $A$ consists of vectors

$\begin{bmatrix}1\\0\\-3\\3\\2\end{bmatrix}, \begin{bmatrix}3\\1\\0\\4\\0\end{bmatrix}, \begin{bmatrix}3\\0\\-1\\1\\-2\end{bmatrix}$ 

Notice that the basis for the column space obtained using Method 1 is different than that obtained using Method 2. These bases both span the column space of $A$ because the columns of $A$ can be written as linear combinations of the vectors in each basis.

That is, write the following 4 column vectors

$\textbf{v}_1=\begin{bmatrix}1&0&-3&3&2\end{bmatrix}^T$,  $\textbf{v}_2=\begin{bmatrix}3&1&0&4&0\end{bmatrix}^T$,  $\textbf{v}_3=\begin{bmatrix}1&1&6&-2&-4\end{bmatrix}^T$, $\textbf{v}_4=\begin{bmatrix}3&0&-1&1&-2\end{bmatrix}^T$ 

as linear combinations of vectors in the set
$$S_1=\left\{\begin{bmatrix}1\\0\\-3\\3\\2\end{bmatrix}, \begin{bmatrix}3\\1\\0\\4\\0\end{bmatrix}, \begin{bmatrix}3\\0\\-1\\1\\-2\end{bmatrix}\right\}=\left\{\textbf{u}_1,\textbf{u}_2,\textbf{u}_3\right\}$$
and
$$S_2=\left\{\begin{bmatrix}1\\0\\0\\0\\-1\end{bmatrix}, \begin{bmatrix}0\\1\\0\\4\\3\end{bmatrix}, \begin{bmatrix}0\\0\\1\\-1\\-1\end{bmatrix}\right\}=\left\{\textbf{w}_1,\textbf{w}_2,\textbf{w}_3\right\}$$

In [ ]:
# v_3 in S_1
A <- matrix(c(1,3,3,0,1,0,-3,0,-1,3,4,1,2,0,-2), 5, 3, byrow = TRUE)
(Ab <- cbind(A,c(1,1,6,-2,-4)))
B <- rref(A)
B

# v_1 in S_2
A <- matrix(c(1,0,0,0,1,0,0,0,1,0,4,-1,-1,3,-1), 5, 3, byrow = TRUE)
(Ab <- cbind(A,c(1,0,-3,3,2)))
B <- rref(Ab)
B

# v_2 in S_2
(Ab <- cbind(A,c(3,1,0,4,0)))
B <- rref(Ab)
B

# v_3 in S_2
(Ab <- cbind(A,c(1,1,6,-2,-4)))
B <- rref(Ab)
B

# v_4 in S_2
(Ab <- cbind(A,c(3,0,-1,1,-2)))
B <- rref(Ab)
B

[,1] [,2] [,3] [,4]
[1,]  1   3     3    1  
[2,]  0   1     0    1  
[3,] -3   0    -1    6  
[4,]  3   4     1   -2  
[5,]  2   0    -2   -4

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1   
[4,] 0    0    0   
[5,] 0    0    0

[,1] [,2] [,3] [,4]
[1,]  1   0     0    1  
[2,]  0   1     0    0  
[3,]  0   0     1   -3  
[4,]  0   4    -1    3  
[5,] -1   3    -1    2

[,1] [,2] [,3] [,4]
[1,] 1    0    0     1  
[2,] 0    1    0     0  
[3,] 0    0    1    -3  
[4,] 0    0    0     0  
[5,] 0    0    0     0

[,1] [,2] [,3] [,4]
[1,]  1   0     0   3   
[2,]  0   1     0   1   
[3,]  0   0     1   0   
[4,]  0   4    -1   4   
[5,] -1   3    -1   0

[,1] [,2] [,3] [,4]
[1,] 1    0    0    3   
[2,] 0    1    0    1   
[3,] 0    0    1    0   
[4,] 0    0    0    0   
[5,] 0    0    0    0

[,1] [,2] [,3] [,4]
[1,]  1   0     0    1  
[2,]  0   1     0    1  
[3,]  0   0     1    6  
[4,]  0   4    -1   -2  
[5,] -1   3    -1   -4

[,1] [,2] [,3] [,4]
[1,] 1    0    0    1   
[2,] 0    1    0    1   
[3,] 0    0    1    6   
[4,] 0    0    0    0   
[5,] 0    0    0    0

[,1] [,2] [,3] [,4]
[1,]  1   0     0    3  
[2,]  0   1     0    0  
[3,]  0   0     1   -1  
[4,]  0   4    -1    1  
[5,] -1   3    -1   -2

[,1] [,2] [,3] [,4]
[1,] 1    0    0     3  
[2,] 0    1    0     0  
[3,] 0    0    1    -1  
[4,] 0    0    0     0  
[5,] 0    0    0     0

For $S_1$, $\textbf{v}_1=\textbf{u}_1,\textbf{v}_2=\textbf{u}_2,\textbf{v}_3=-2\textbf{u}_1+\textbf{u}_2,\textbf{v}_4=\textbf{u}_3$.

For $S_2$, $\textbf{v}_1=\textbf{w}_1-3\textbf{w}_3,\textbf{v}_2=3\textbf{w}_1+\textbf{w}_2$, $\textbf{v}_3=\textbf{w}_1+\textbf{w}_2+6\textbf{w}_3$, and $\textbf{v}_4=3\textbf{w}_1-\textbf{w}_3$.


###Theorem 4.15: Row and Column Spaces Have Equal Dimensions
The row space and column space of an $m\times n$ matrix $A$ have the same dimension.

##Definition of the Rank of a Matrix
The dimension of the row (or column) space of a matrix $A$ is the **rank** of $A$ and is denoted by $\text{rank} (A)$.


##Definition: Solutions of a Homogeneous System
If $A$ is an $m\times n$ matrix, then the set of all solutions of the homogeneous system of linear equations $A\textbf{x}=\textbf{0}$ is a subspace of $\mathbb{R}^n$ called the **nullspace** of $A$ and is denoted by $N(A)$. So,
$$N(A)=\{\textbf{x}\in\mathbb{R}^n:A\textbf{x}=\textbf{0}\}.$$
The dimension of the nullspace of $A$ is the **nullity** of $A$.

####$\star$Example
Find the nullspace of the matrix.
$$A=\begin{bmatrix}1&2&-2&1\\3&6&-5&4\\1&2&0&3\end{bmatrix}$$

**Solution**
The nullspace of $A$ is the solution space of the homogeneous system
$$A\textbf{x}=\textbf{0}.$$
To solve this system, find the reduced row-echelon form of the augmented matrix $[A\:\:\:\textbf{0}]$.


In [ ]:
A <- matrix(c(1,2,-2,1,3,6,-5,4,1,2,0,3), 3, 4, byrow = TRUE)
(Ab <- cbind(A,c(0,0,0)))
B <- rref(Ab)
B

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    -2   1    0   
[2,] 3    6    -5   4    0   
[3,] 1    2     0   3    0

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    0    3    0   
[2,] 0    0    1    1    0   
[3,] 0    0    0    0    0

The system of equations corresponding to the reduced row-echelon form is
\begin{alignat*}{4}
    x_1 &  {}+{} 2x_2 & {}{}& {}{} & {}+{} & 3x_4  &= 0\\
    & {}{}       & {}{}  & x_3 &  {}+{} &x_4&= 0\\
\end{alignat*}

Choose $x_2$ and $x_4$ as free variables to represent the solutions in parametric form.
$$x_1=-2s-3t,\:\:x_2=s,\:\:x_3=-t,\:\:x_4=t$$
This means that the solution space of $A\textbf{x}=\textbf{0}$ consists of all solution vectors of the form
$$\textbf{x}=\begin{bmatrix}x_1\\x_2\\x_3\\x_4\end{bmatrix}=\begin{bmatrix}-2s-3t\\s\\-t\\t\end{bmatrix}=s\begin{bmatrix}-2\\1\\0\\0\end{bmatrix}+t\begin{bmatrix}-3\\0\\-1\\1\end{bmatrix}$$
Thus, a basis for the nullspace of $A$ consists of the vectors
$\begin{bmatrix}-2\\1\\0\\0\end{bmatrix}$ and $\begin{bmatrix}-3\\0\\-1\\1\end{bmatrix}$.


###Theorem 4.16: Dimension of the Solution Space
If $A$ is an $m\times n$ matrix of rank $r$, then the dimension of the solution space of $A\textbf{x}=\textbf{0}$ is $n-r$. That is, $$n=\text{rank}(A)+\text{nullity}(A).$$

In [ ]:
#Find the rank and nullity of A, and a subset of the column vectors of A that forms a basis for the column space of A.
A <- matrix(c(1,0,-2,1,0,0,-1,-3,1,3,-2,-1,1,-1,3,0,3,9,0,-12), 4, 5, byrow = TRUE)
B <- rref(A)
B

[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    -2   0     1  
[2,] 0    1     3   0    -4  
[3,] 0    0     0   1    -1  
[4,] 0    0     0   0     0

$B$ has three nonzero rows, so the rank of $A$ is 3. Also, the number of columns of $A$ is $n=5$, which implies that the nullity of $A$ is $n-\text{rank}=5-3=2.$

The first, second, and fourth column vectors of $B$ are linearly independent, so the corresponding column vectors of $A$,
$$\begin{bmatrix}1\\0\\-2\\0\end{bmatrix},\begin{bmatrix}0\\-1\\-1\\3\end{bmatrix},\begin{bmatrix}1\\1\\-1\\0\end{bmatrix}$$
form a basis for the column space of $A$.

###Theorem 4.17: Solutions of a Nonhomogeneous Linear System
If $\textbf{x}_p$ is a particular solution of the nonhomogeneous system $A\textbf{x}=\textbf{b}$, then every solution of this system can be written in the form $\textbf{x}=\textbf{x}_p+\textbf{x}_h$, where $\textbf{x}_h$ is a solution of the corresponding homogeneous system $A\textbf{x}=\textbf{0}$.

####$\star$Example
Find the set of all solution vectors of the system of linear equations.
\begin{alignat*}{4}
    x_1 & {}{} &      & {}-{} & 2x_3 & {}+{} x_4  &=& 5\\
   3x_1 & {}+{} & x_2 & {}-{} & 5x_3 & {}{}       &=& 8\\
    x_1 & {}+{} & 2x_2 & {}{} &      & {}-{} 5x_4 &=& -9\\
\end{alignat*}

In [ ]:
(A <- matrix(c(1,0,-2,1,5,3,1,-5,0,8,1,2,0,-5,-9), 3, 5, byrow = TRUE))
B <- rref(A)
B

[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    -2    1    5  
[2,] 3    1    -5    0    8  
[3,] 1    2     0   -5   -9

[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    -2    1    5  
[2,] 0    1     1   -3   -7  
[3,] 0    0     0    0    0

The system of equations corresponding to the reduced row-echelon form is
\begin{alignat*}{4}
    x_1 & {}{} &      & {}-{} & 2x_3 & {}+{} x_4  &=& 5\\
        & {}{} & x_2 & {}+{} & x_3 & {}-{} 3x_4      &=& -7\\
\end{alignat*}

Choose $x_3=s$ and $x_4=t$, write a representative solution vector of $A\textbf{x}=\textbf{b}$ as shown below.
$$\textbf{x}=\begin{bmatrix}x_1\\x_2\\x_3\\x_4\end{bmatrix}=\begin{bmatrix}5+2s-t\\-7-s+3t\\0+s+0t\\0+0s+t\end{bmatrix}=\begin{bmatrix}5\\-7\\0\\0\end{bmatrix}+s\begin{bmatrix}2\\-1\\1\\0\end{bmatrix}+t\begin{bmatrix}-1\\3\\0\\1\end{bmatrix}=\textbf{x}_p+s\textbf{u}_1+t\textbf{u}_2$$
$\textbf{x}_p$ is a particular solution vector of $A\textbf{x}=\textbf{b}$, and $\textbf{x}_h=s\textbf{u}_1+t\textbf{u}_2$ represents an arbitrary vector in the solution space of $A\textbf{x}=\textbf{b}$.


###Theorem 4.18: Solutions of a System of Linear Equations
The system $A\textbf{x}=\textbf{0}$ is consistent if and only if $\textbf{b}$ is in the column space of $A$.


###Summary of Equivalent Conditions for Square Matrices
If $A$ is an $n\times n$ matrix, then the statements below are equivalent.
1. $A$ is invertible.
2. $A\textbf{x}=\textbf{b}$ has a unique solution for every $n\times 1$ column matrix \textbf{b}.
3. $A\textbf{x}=\textbf{0}$ has only the trivial solution.
4. $A$ is row-equivalent to $I_n$.
5. $\det(A)\neq 0$
6. $\text{rank}(A)=n$
7. The $n$ row vectors of $A$ are linearly independent.
8. The $n$ column vectors of $A$ are linearly independent.