<a href="https://colab.research.google.com/github/madonnaojorin/MAT343_Linear_Algebra/blob/main/4-7_Coordinates_Change_of_Basis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#4.7. Coordinates and Change of Basis

In [5]:
install.packages("pracma")
library(pracma)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



##Definition: Coordinate Representation Relative to a Basis
Let $B=\{\textbf{v}_1,\textbf{v}_2,\ldots,\textbf{v}_n\}$ be an ordered basis for a vector space $V$ and let $\textbf{x}$ be a vector in $V$ such that
$$\textbf{x}=c_1\textbf{v}_1+c_2\textbf{v}_2+c_n\textbf{v}_n.$$
The scalars $c_1,c_2,\ldots,c_n$ are the **coordinates of** $\textbf{x}$ **relative to the basis** $B$. The **coordinate matrix** (or **coordinate vector**) **of** $\textbf{x}$ **relative to** $B$ is the column matrix in $\mathbb{R}^n$ whose components are the coordinates of $\textbf{x}$.
$$[\textbf{x}]_B=\begin{bmatrix}c_1\\c_2\\\vdots\\c_n
\end{bmatrix}$$

####$\star$Example
(a) Find the coordinate matrix of $\textbf{x}=\langle -2,1,3\rangle$ in $\mathbb{R}^3$ relative to the standard basis $$S=\{\langle 1,0,0 \rangle,\langle 0,1,0\rangle,\langle 0,0,1\rangle\}$$

**Solution:**

$$\textbf{x}=\langle-2,1,3\rangle=-2\langle 1,0,0 \rangle+1\langle 0,1,0\rangle+3\langle 0,0,1\rangle$$

Therefore, the coordinate matrix of $\textbf{x}$ relative to the standard basis is simply
$$[\textbf{x}]_S=\begin{bmatrix}-2\\1\\3\end{bmatrix}.$$


(b) The coordinate matrix of $\textbf{x}$ in $\mathbb{R}^2$ relative to the ordered basis $$B=\{\textbf{v}_1,\textbf{v}_2\}=\{\langle 1,0 \rangle,\langle 1,2\rangle\}$$
is $$[\textbf{x}]_B=\begin{bmatrix}3\\2\end{bmatrix}.$$

Find the coordinate matrix of $\textbf{x}$ relative to the standard basis $$B'=\{\textbf{u}_1,\textbf{u}_2\}=\{\langle 1,0 \rangle,\langle 0,1\rangle\}$$

**Solution:**

$$\textbf{x}=3\textbf{v}_1+2\textbf{v}_2=3\langle 1,0 \rangle+2\langle 1,2\rangle=\langle 5,4 \rangle=5\langle 1,0 \rangle+4\langle 0,1 \rangle$$

Therefore, the coordinate matrix of $\textbf{x}$ relative to the standard basis is simply
$$[\textbf{x}]_{B'}=\begin{bmatrix}5\\4\end{bmatrix}.$$

###Theorem 4.19: The Inverse of a Transition Matrix
If $P$ is the transition matrix from a basis $B'$ to a basis $B$ in $\mathbb{R}^n$, then $P$ is invertible and the transition matrix from $B$ to $B'$ is $P^{-1}$.

###Lemma
Let $B=\{\textbf{v}_1,\textbf{v}_2,\ldots,\textbf{v}_n\}$ and $B'=\{\textbf{u}_1,\textbf{u}_2,\ldots,\textbf{u}_n\}$  be two bases for a vector space $V$. If
\begin{align*}
    \textbf{v}_1&=c_{11}\textbf{u}_1+c_{21}\textbf{u}_2+\cdots+c_{n1}\textbf{u}_n\\
    \textbf{v}_2&=c_{12}\textbf{u}_1+c_{22}\textbf{u}_2+\cdots+c_{n2}\textbf{u}_n\\
    &\vdots\\
    \textbf{v}_n&=c_{1n}\textbf{u}_1+c_{2n}\textbf{u}_2+\cdots+c_{nn}\textbf{u}_n\\
\end{align*}

then the transition matrix from $B$ to $B'$ is
$$Q=\begin{bmatrix}
c_{11}&c_{12}&\cdots&c_{1n}\\
c_{21}&c_{22}&\cdots&c_{2n}\\
\vdots&\vdots&&\vdots\\
c_{n1}&c_{n2}&\cdots&c_{nn}\\
\end{bmatrix}$$


###Theorem 4.12: Transition Matrix from $B$ to $B'$
Let $$B=\{\textbf{v}_1,\textbf{v}_2, \ldots,\textbf{v}_n\}$$
and
$$B'=\{\textbf{u}_1,\textbf{u}_2, \ldots,\textbf{u}_n\}$$

be two bases for $\mathbb{R}^n$. Then the transition matrix $P^{-1}$ from $B$ to $B'$ can be found by using Gauss-Jordan elimination on the $n\times 2n$ matrix $[B\:\:\:B']$, as shown below.
$$[B'\:\:\:B]⇒[I_n\:\:\:P^{-1}]$$



####$\star$Example
Find the transition matrix from $B$ to $B'$ for the bases for $\mathbb{R}^n$ below.

$$B=\{\langle 1,0,0\rangle,\langle 0,1,0\rangle,\langle 0,0,1\rangle\}$$
and
$$B=\{\langle 1,0,1\rangle,\langle 0,-1,2\rangle,\langle 2,3,-5\rangle\}$$

**Solutions:**

$$B=\begin{bmatrix}1&0&0\\0&1&0\\0&0&1\end{bmatrix},\:\:\:\:B'=\begin{bmatrix}1&0&1\\0&-1&2\\2&3&-5\end{bmatrix}$$

$$[B'\:\:\: B]=\begin{bmatrix}1&0&1&1&0&0\\0&-1&2&0&1&0\\2&3&-5&0&0&1\end{bmatrix}⇒\begin{bmatrix}1&0&0&-1&3&1\\0&1&0&4&-7&-2\\0&0&1&2&-3&-1\end{bmatrix}$$
The transition matrix from $B$ to $B'$ is
$$P^{-1}=\begin{bmatrix}-1&3&1\\4&-7&-2\\2&-3&-1\end{bmatrix}.$$

In [6]:
(B_ <- matrix(c(1,0,1,0,-1,2,2,3,-5), 3, 3, byrow = TRUE))
(B <- matrix(c(1,0,0,0,1,0,0,0,1),3 ,3, byrow = TRUE))
(B_B <- cbind(B_,B))
rref(B_B)
# Check 
inv(B_)

[,1] [,2] [,3]
[1,] 1     0    1  
[2,] 0    -1    2  
[3,] 2     3   -5

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1     0    1   1    0    0   
[2,] 0    -1    2   0    1    0   
[3,] 2     3   -5   0    0    1

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    0    0    -1    3    1  
[2,] 0    1    0     4   -7   -2  
[3,] 0    0    1     2   -3   -1