<a href="https://colab.research.google.com/github/madonnaojorin/MAT343_Linear_Algebra/blob/main/5-3_Gram_Schmidt_Process.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#5.3. Orthonormal Bases: Gram-Schmidt Process

##Definitions of Orthogonal and Orthonormal Sets
A set $S$ of vectors in an inner product space $V$ is **orthogonal** when every pair of vectors in $S$ is orthogonal. If, in addition, each vector in the set is a unit vector, then $S$ is **orthonormal**.

In [ ]:
#Show that the set is an orthonormal basis for R^3.

v1 = c(1/sqrt(2),1/sqrt(2),0)
v2 = c(-sqrt(2)/6,sqrt(2)/6,2*sqrt(2)/3)
v3 = c(2/3,-2/3,1/3)

# First show that the three vectors are mutually orthogonal.
v1%*%v2
v1%*%v3
v2%*%v3

# Now, show that each vector is of length 1
norm(v1,type = "2")
norm(v2,type = "2")
norm(v3,type = "2")

# Thus, S is an orthonormal set.
# The three vectors do not lie in the same plane, so S span R^3. 
# By Theorem 4.12, they form a (nonstandard) orthonormal basis for R^3.

[,1]
[1,] 0

[,1]
[1,] 0

[,1]
[1,] 0

[1] 1

[1] 1

[1] 1

###Theorem 5.10 Orthogonal Sets Are Linearly Independent
If $S=\{\textbf{v}_1,\textbf{v}_2,\ldots,\textbf{v}_n\}$ is an orthogonal set of *nonzero* vectors in an inner product space $V$, then $S$ is linearly independent.

###Theorem 5.10 Corollary
If $V$ is an inner product space of dimension $n$, then any orthogonal set of $n$ nonzero vectors is a basis for $V$.


In [ ]:
#Show that the set S below is a basis for R^4.

v1 = c(2,3,2,-2)
v2 = c(1,0,0,1)
v3 = c(-1,0,2,1)
v4 = c(-1,2,-1,1)

# The set S has four nonzero vectors. By the corollary to Theorem 5.10,
# we show that S is a basis for R^4 by showing that it is an orthogonal set.

v1%*%v2
v1%*%v3
v1%*%v4
v2%*%v3
v2%*%v4
v3%*%v4

# Since all innner products are 0,S is orthogonal, 
# and by the corollary to Theorem 5.10, it is a basis for R^4.

[,1]
[1,] 0

[,1]
[1,] 0

[,1]
[1,] 0

[,1]
[1,] 0

[,1]
[1,] 0

[,1]
[1,] 0

###Theorem 5.11 Coordinates Relative to an Orthonormal Basis
If $B=\{\textbf{v}_1,\textbf{v}_2,\ldots,\textbf{v}_n\}$ is an orthonormal basis for an inner product space $V$, then the coordinate representation of a vector $\textbf{w}$ relative to $B$ is
$$\textbf{w}=\langle \textbf{w},\textbf{v}_1\rangle \textbf{v}_1+\langle \textbf{w},\textbf{v}_2\rangle \textbf{v}_2+\cdots+\langle \textbf{w},\textbf{v}_n\rangle \textbf{v}_n.$$

###Theorem 5.12 Gram-Schmidt Orthonormalization Process
1. Let $B=\{\textbf{v}_1,\textbf{v}_2,\ldots,\textbf{v}_n\}$ be a basis for an inner product space $V$.
2. Let $B'=\{\textbf{w}_1,\textbf{w}_2,\ldots,\textbf{w}_n\}$, where
\begin{align*}
    \textbf{w}_1&=\textbf{v}_1\\
    \textbf{w}_2&=\textbf{v}_2-\frac{\langle \textbf{v}_2,\textbf{w}_1\rangle}{\langle \textbf{w}_1,\textbf{w}_1\rangle} \textbf{w}_1\\
    \textbf{w}_3&=\textbf{v}_3-\frac{\langle \textbf{v}_3,\textbf{w}_1\rangle}{\langle \textbf{w}_1,\textbf{w}_1\rangle} \textbf{w}_1-\frac{\langle \textbf{v}_3,\textbf{w}_2\rangle}{\langle \textbf{w}_2,\textbf{w}_2\rangle} \textbf{w}_2\\
    \vdots\\
    \textbf{w}_n&=\textbf{v}_n-\frac{\langle \textbf{v}_n,\textbf{w}_1\rangle}{\langle \textbf{w}_1,\textbf{w}_1\rangle} \textbf{w}_1-\frac{\langle \textbf{v}_n,\textbf{w}_2\rangle}{\langle \textbf{w}_2,\textbf{w}_2\rangle} \textbf{w}_2-\cdots-\frac{\langle \textbf{v}_n,\textbf{w}_{n-1}\rangle}{\langle \textbf{w}_{n-1},\textbf{w}_{n-1}\rangle} \textbf{w}_{n-1}\\
\end{align*}
Then $B'$ is an *orthogonal* basis for $V$.
3. Let $\textbf{u}_i=\frac{\textbf{w}_i}{||\textbf{w}_i||}$. Then $B''=\{\textbf{u}_1,\textbf{u}_2,\ldots,\textbf{u}_n\}$ is an *orthonormal* basis for $V$.
Also, $\text{span}\{\textbf{v}_1,\textbf{v}_2,\ldots,\textbf{v}_k\}=\text{span}\{\textbf{u}_1,\textbf{u}_2,\ldots,\textbf{u}_k\}$ for $k=1,2,\ldots,n$.


In [2]:
gramschmidt <- function(x) {
  # Get the number of rows and columns of the matrix
  n <- ncol(x)
  m <- nrow(x)
  
  # Initialize the Q and R matrices
  Q <- matrix(0, m, n)
  R <- matrix(0, n, n)
  
  for (j in 1:n) {
    v = x[,j] # Step 1 of the Gram-Schmidt process v1 = a1
    # Skip the first column
    if (j > 1) {
      for (i in 1:(j-1)) {
        R[i,j] <- t(Q[,i]) %*% x[,j] # Find the inner product (noted to be q^T a earlier)
        # Subtract the projection from v which causes v to become perpendicular to all columns of Q
        v <- v - R[i,j] * Q[,i] 
      }      
    }
    # Find the L2 norm of the jth diagonal of R
    R[j,j] <- sqrt(v%*%v)
    # The orthogonalized result is found and stored in the ith column of Q.
    Q[,j] <- v / R[j,j]
  }
  return(Q)
}

In [ ]:
# Find the basis B
v1 = c(1,1)
v2 = c(0,1)
A <- matrix(c(v1,v2), 2, length(v1), byrow = FALSE)

(Q = gramschmidt(A))

[,1]      [,2]      
[1,] 0.7071068 -0.7071068
[2,] 0.7071068  0.7071068

For a square matrix $A$ the QR Decomposition converts $A$ into the product of an orthogonal matrix $Q$ (i.e. $Q^TQ=I$)
 and an upper triangular matrix $R$. Hence:
 $$A=QR$$

where column $i$ of the $m\times m$ matrix $R$ contains the coefficients of the linear combination of $\textbf{q}_j$’s that produces $\textbf{a}_i$. $Q$ is a $\mathbb{R}^{n\times m}$ matrix with $Q^TQ = I_{m\times m}$.
By the proof of Gram-Schmidt, $\textbf{a}_i \in span(\textbf{q}_1, \cdots,\textbf{q}_i)$. So column $i$ of $R$ has
only zeros below the diagonal. Hence $R$ has a special structure: it is upper triangular.

In [ ]:
R = t(Q)%*%A

(QR = Q %*% R)

[,1] [,2]         
[1,] 1    -1.008758e-16
[2,] 1     1.000000e+00

In [ ]:
# Apply the Gram-Schmidt orthonormalization process to the basis B for R^3 below.
v1 = c(1,1,0)
v2 = c(1,2,0)
v3 = c(0,1,2)
A <- matrix(c(v1,v2,v3), 3, length(v1), byrow = FALSE)

(Q = gramschmidt(A))

[,1]      [,2]       [,3]         
[1,] 0.7071068 -0.7071068  0.000000e+00
[2,] 0.7071068  0.7071068 -1.110223e-16
[3,] 0.0000000  0.0000000  1.000000e+00

In [3]:
# 6 column vectors in 4D, only 3 are independent
v1 = c(1, 1, 2, 0, 1, 1)
v2 = c(0, 0, 0, 1, 2, 1)
v3 = c(1, 2, 3, 1, 3, 2)
v4 = c(1, 0, 1, 0, 1, 1)
A <- matrix(c(v1,v2,v3,v4), 4, length(v1), byrow = FALSE)

(Q = gramschmidt(A))

[,1]      [,2]       [,3]          [,4]       [,5]       [,6]        
[1,] 0.4082483  0.5773503 -4.082483e-01 -0.1163470  0.4434659  0.574815807
[2,] 0.4082483  0.5773503  4.082483e-01  0.6592995 -0.8570907 -0.560766589
[3,] 0.8164966 -0.5773503 -5.892206e-16 -0.2539081  0.1934288 -0.006570022
[4,] 0.0000000  0.0000000  8.164966e-01  0.6980818 -0.1769713  0.595889634