<a href="https://colab.research.google.com/github/madonnaojorin/MAT343/blob/main/Gaussian_Elimination.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Row-Echelon Form and Reduced Row-Echelon Form
A matrix in **row-schelon form** has the properties below.


1.   Any rows consisting entirely of zeros occur at the bottom of the matrix.
2.   For each row that does not consist entirely of zeros, the first nonzero entry is 1 (called a leading 1).
3.   For two successive (nonzero) rows, the leading 1 in the higher row is farther to the left than the leading 1 in the lower row.

A matrix in row-echelon form is in **reduced row-schelon form** when every column that has a leading 1 has zeros in every position above and below its leading 1. 



#Elementary Row Operations


1.   Interchange two rows.
2.   Multiply a row by a nonzero constant.
3.   Add a multiple of a row to another row.



#Gaussian Elimination 
Gaussian elimination is a method for solving systems of equations in matrix form.<br>
**Goal**: turn matrix into row-echelon form 
  $$\begin{bmatrix}
   1 & a & b & d \\
   0 & 1 & c & e \\
   0 & 0 & 1 & f \\
\end{bmatrix}$$
Once in this form, we can say that $z=f$ and use back substitution to solve for $y$ and $x$.<br>
Use the elementary row operations and follow these steps:
 

1.   Get a 1 in the i-th column, i-th row
2.   Use the 1 to get 0’s in the remainder of the i-th column
3.   Repest the same steps for i+1-th

#Gauss-Jordan Elimination 
Gauss-Jordan elimination is another method for solving systems of equations in matrix form. It is really a continuation of Gaussian elimination.<br>
**Goal**: turn matrix into reduced row-echelon form 
  $$\begin{bmatrix}
   1 & 0 & 0 & a \\
   0 & 1 & 0 & b \\
   0 & 0 & 1 & c \\
\end{bmatrix}$$
Once in this form, we can say that $x=a, y=b, z=c$ (no need to do back-substitution).<br>
Use the elementary row operations as before.

#Implementing in R
Let's sole the following system using Gauss-Jordan elimination.
\begin{eqnarray}
2x-5y+5z&=&17\\
x-2y+3z&=&9\\
-x+3y\hspace{11mm}&=&-4
\end{eqnarray}

In [ ]:
# Set a matrix that you want to solve
(a <- matrix (c(2,-5,5,17,1,-2,3,9,-1,3,0,-4), 3, 4, byrow = T))

[,1] [,2] [,3] [,4]
[1,]  2   -5   5    17  
[2,]  1   -2   3     9  
[3,] -1    3   0    -4

####Implementing Elementary Operations

1.   Op_multiply <br>
Multiply a row by a nonzero constant.
2.   Op_add <br>
Add a multiple of a row to another row.<br>

Applying an elementary row operation to a matrix is equivalent to premultiplying the matrix by an elementary matrix, which are computed in R by



In [ ]:
Op_multiply <- function (n, i, x) {
  s <- diag (n)
  s [i, i] <- x
  return (s)
}

Op_add <- function (n, i, j, x) {
  t <- diag (n)
  t [i, j] <- x
  return (t)    
}

In [ ]:
# Identity matrix of size n=3
diag (3)

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

In [ ]:
sfunc (3, 1, 1 / a[1, 1])

[,1] [,2] [,3]
[1,] 0.5  0    0   
[2,] 0.0  1    0   
[3,] 0.0  0    1

In [ ]:
# Get a 1 in the first column, first row
(a <- sfunc (3, 1, 1 / a[1, 1]) %*% a)

[,1] [,2] [,3] [,4]
[1,]  1   -2.5 2.5   8.5
[2,]  1   -2.0 3.0   9.0
[3,] -1    3.0 0.0  -4.0

In [ ]:
gaussMatrixForward <- function (a, verbose = TRUE) {
  n <- nrow (a)
    for (i in 1 : n) {
        a <- Op_multiply (n, i, 1 / a[i, i]) %*% a
    if (verbose) {
      print (noquote (formatC (a, digits = 4, width = 7, format = "f")))
    }
        if (i == n) {
            break ()
        }
        for (j in (i + 1) : n) {
            a <- Op_add (n, j, i, - a[j, i]) %*% a
      if (verbose) {
        print (noquote (formatC (a, digits = 4, width = 7, format = "f")))
      }
        }
    }
    return (a)
}

In [ ]:
row_echelon <- gaussMatrixForward (cbind(a,diag(3)))

     [,1]    [,2]    [,3]    [,4]    [,5]    [,6]    [,7]   
[1,]  1.0000 -2.5000  2.5000  8.5000  0.5000  0.0000  0.0000
[2,]  1.0000 -2.0000  3.0000  9.0000  0.0000  1.0000  0.0000
[3,] -1.0000  3.0000  0.0000 -4.0000  0.0000  0.0000  1.0000
     [,1]    [,2]    [,3]    [,4]    [,5]    [,6]    [,7]   
[1,]  1.0000 -2.5000  2.5000  8.5000  0.5000  0.0000  0.0000
[2,]  0.0000  0.5000  0.5000  0.5000 -0.5000  1.0000  0.0000
[3,] -1.0000  3.0000  0.0000 -4.0000  0.0000  0.0000  1.0000
     [,1]    [,2]    [,3]    [,4]    [,5]    [,6]    [,7]   
[1,]  1.0000 -2.5000  2.5000  8.5000  0.5000  0.0000  0.0000
[2,]  0.0000  0.5000  0.5000  0.5000 -0.5000  1.0000  0.0000
[3,]  0.0000  0.5000  2.5000  4.5000  0.5000  0.0000  1.0000
     [,1]    [,2]    [,3]    [,4]    [,5]    [,6]    [,7]   
[1,]  1.0000 -2.5000  2.5000  8.5000  0.5000  0.0000  0.0000
[2,]  0.0000  1.0000  1.0000  1.0000 -1.0000  2.0000  0.0000
[3,]  0.0000  0.5000  2.5000  4.5000  0.5000  0.0000  1.0000
     [,1]    [,2]    [,3

In [ ]:
gaussMatrixBackward <- function (a, verbose = TRUE) {
  n <- nrow (a)
    for (i in n : 2) {
        for (j in (i - 1) : 1) {
            a <- Op_add (n, j, i, - a[j, i]) %*% a
      if (verbose) {
        print (noquote (formatC (a, digits = 4, width = 7, format = "f")))
      }
        }
    }
    return (a)
}

In [ ]:
reduced_row_echelon <- gaussMatrixBackward (row_echelon)

     [,1]    [,2]    [,3]    [,4]    [,5]    [,6]    [,7]   
[1,]  1.0000 -2.5000  2.5000  8.5000  0.5000  0.0000  0.0000
[2,]  0.0000  1.0000  0.0000 -1.0000 -1.5000  2.5000 -0.5000
[3,]  0.0000  0.0000  1.0000  2.0000  0.5000 -0.5000  0.5000
     [,1]    [,2]    [,3]    [,4]    [,5]    [,6]    [,7]   
[1,]  1.0000 -2.5000  0.0000  3.5000 -0.7500  1.2500 -1.2500
[2,]  0.0000  1.0000  0.0000 -1.0000 -1.5000  2.5000 -0.5000
[3,]  0.0000  0.0000  1.0000  2.0000  0.5000 -0.5000  0.5000
     [,1]    [,2]    [,3]    [,4]    [,5]    [,6]    [,7]   
[1,]  1.0000  0.0000  0.0000  1.0000 -4.5000  7.5000 -2.5000
[2,]  0.0000  1.0000  0.0000 -1.0000 -1.5000  2.5000 -0.5000
[3,]  0.0000  0.0000  1.0000  2.0000  0.5000 -0.5000  0.5000
